name: Plugin asset/readme update

on:
  push:
    branches:
      - develop
    paths:
      - "readme.txt"
      - "readme.md"
      - ".wordpress-org/**"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  assets:
    name: Update assets and readme
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: WordPress.org plugin asset/readme update
        uses: 10up/action-wordpress-plugin-asset-update@stable
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SLUG: thrivedesk
